### ISSUE TITLE
2 Comments about MCPModPack

### ISSUE THREAD

**Issue by Robbie10538** [medianainc/MCPModPack#1]
For the simulation function (MCPModSimulation)
- how is the go probability (along with the go_threshold) defined exactly? (I don't believe anything as such was defined in the original Bretz paper) Maybe I'm missing something but it seems to not be immediately clear how this is defined- is it the probability the treatment effect under the model at the chosen dose is > the go_threshold?
- it would be nice to have an option to plot the fitted dose response relationships with corresponding CIs (using the data in the $sim_results output of the simulation function). Update: I now see this is available on the App. Is there a way to get this easily from the MCPModSimulation function output?

**Comment by medianainc** [comment]
Thank you for downloading the package. Please see the responses below:

1. Go probability. We will update the documentation for to clarify that the go probability is defined as the probability that the maximum effect for the best dose-response model exceeds a pre-defined value (go_threshold). 

2. These plots (fitted dose response curves with confidence bands) are included in simulation reports generated by the SimulationReport function and you can directly access the data used in these plots. If res is an object created by the MCPModSimulation function, you will find three matrices in results$sim_results (dose_response_lower, dose_response_mean, dose_response_upper). Each column in each matrix defines the lower limit, fitted curve and upper limits for each dose-response model, respectively.
