### ISSUE TITLE
R-Shiny simulation app failure to execute when only 1 model selected

### ISSUE THREAD

**Issue by octa-consulting** [medianainc/MCPModPack#2]
Hi
For training purposes I wanted to create a scenario in which only 1 candidate model is selected (in my case, Emax) and I received the following error message (in the RStudio Console) and the simulation app wouldn't produce any output
Warning: Error in ContrastStep: object 'corr_matrix' not found
My workaround was to request an additional model (eg SigEmax)
I attach a report file of a successfully run scenario (i.e. I specified both Emax and SigEmax) so that you can see the parameter values for the Emax model in case you wish to replicate the issue
[MCPModPack_Report.docx](https://github.com/medianainc/MCPModPack/files/5452557/MCPModPack_Report.docx)

Thanks
Nelson Kinnersley

**Comment by alexdmitrienko** [comment]
Hi Nelson, thank you for pointing this out. This issue has been addressed in the latest update.
