### ISSUE TITLE
Problem with loading and running MCPModPack - Error messages

### ISSUE THREAD

**Issue by bekif** [medianainc/MCPModPack#4]
Error trying to load newly installed MCPModPack as below (the installation seems to occur fine):

Error: package or namespace load failed for ‘MCPModPack’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘xfun’ 0.26 is being loaded, but >= 0.29 is required

Meaning none of the functions run, e.g. when trying to run MCPModAnalysis(.....), I get the following error:
Error: package or namespace load failed for ‘MCPModPack’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘xfun’ 0.26 is being loaded, but >= 0.29 is required

Similarly with the SimulationApp():
Warning: Error in MCPModRunSimulations: object '_MCPModPack_MCPModRunSimulations' not found

**Comment by vicdmitrienko** [comment]
1. What OS do you use?
2. What is the version of R?
3. Is RTools installed on your computer? Provide your version, please? (https://cran.r-project.org/bin/windows/Rtools/)
4. Is package 'devtools' installed?
5. From which source are you install MCPModPack? From CRAN or from GitHub?

**Comment by bekif** [comment]
My mistake! I thought I had updated xfun but it hadn't worked. It has now worked and the package runs as normal. Thank you.
